config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :artists, :songs
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :songs

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :artist

  def artist_name
    if self.artist
      self.artist.name
    else
      ""
    end
  end

  def artist_name=(name)
    self.artist = Artist.find_or_create_by(name: name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def index
   end

   def show
     @artist = Artist.find(params[:id])
   end

   def new
     @artist = Artist.new
   end

   def create
     @artist = Artist.new(artist_params)

     if @artist.save
       redirect_to @artist
     else
       render :new
     end
   end

   def edit
     @artist = Artist.find(params[:id])
   end

   def update
     @artist = Artist.find(params[:id])

     @artist.update(artist_params)

     if @artist.save
       redirect_to @artist
     else
       render :edit
     end
   end

   def destroy
     @artist = Artist.find(params[:id])
     @artist.destroy
     flash[:notice] = "Artist deleted."
     redirect_to artists_path
   end

   private

   def artist_params
     params.require(:artist).permit(:name)
   end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def show
    @song = Song.find(params[:id])
  end

  def new
    @song = Song.new
  end

  def create
    @song = Song.new(song_params)

    if @song.save
      redirect_to @song
    else
      render :new
    end
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    @song.update(song_params)

    if @song.save
      redirect_to @song
    else
      render :edit
    end
  end

  def destroy
    @song = Song.find(params[:id])
    @song.destroy
    flash[:notice] = "Song deleted."
    redirect_to songs_path
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist_name)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def display_artist(song)
        if song.artist
          link_to song.artist.name, song.artist
        else
          link_to 'Add Artist', edit_song_path(song)
        end
      end
end

app/helpers/artists_helper.rb
module ArtistsHelper
  def display_artist(song)
    if song.artist
      link_to song.artist.name, artist_path(song.artist)
    else
      link_to "Add Artist", edit_song_path(song)
    end
  end
end

app/helpers/songs_helper.rb
module SongsHelper


end

app/views/artists/_artist.html.erb
<h3><%=link_to artist.name, artist_path(artist)%></h3>

app/views/artists/_form.html.erb
<%= form_for @artist  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/artists/_link.html.erb
<h2><%= link_to artist.name, artist %></h2>

app/views/artists/edit.html.erb
<h1>Editing <%= @artist.name %></h1>

<%= render 'form' %>

app/views/artists/index.html.erb
<ul>
<% @artist.each do |art| %>
  <li><%= link_to art.name, artist_path(art) %></li>
<% end %>
</ul>
<br>
<%= link_to "Add New Artist", new_artist_path %>

app/views/artists/new.html.erb
<h1>Create an Artist</h1>

<%= form_for @artist  do |f| %>
<%= f.label :name %>
<%= f.text_field :name %>
<br/>

<%= f.submit %>
<% end %>

app/views/artists/show.html.erb
<h1><%= @artist.name %></h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flatiron Tunes</title>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <% flash.each do |name, msg| -%>
      <%= content_tag :div, msg, class: name %>
    <% end -%>
    <%= yield %>
  </body>
</html>

app/views/songs/_add_artist.html.erb
<%= link_to "Add Artist", edit_song_path(song) %>

app/views/songs/_form.html.erb
<%= form_for @song  do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :artist_name %>
  <%= f.text_field :artist_name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/songs/_index.html.erb
<ul>
  <li><%= link_to song.title, song_path(song) %> - <%= display_artist(song) %></li>
</ul>

app/views/songs/_info.html.erb
<%= link_to song.title, song_path(song) %>
<%= display_artist(song) %>

app/views/songs/_show_artist.html.erb
<%= link_to song.artist.name, song.artist %>

app/views/songs/_song.html.erb
<%= link_to song.title, song_path(song) %>

app/views/songs/_song_artist.html.erb
<% if song.artist == nil || song.artist.name == "" %>
  <%= link_to "Add Artist", edit_song_path(song) %><br>
<% else %>
  <%= render partial: 'artists/artist', locals: {artist: song.artist} %>
<% end %>

app/views/songs/_song_info.html.erb
<%= link_to song.title, song_path(song) %>
<%= display_artist(song) %>

app/views/songs/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsProgrammerProfilePartials</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= analytics_init if Rails.env.production? %>
</head>
<body>

<%= render 'layouts/navbar' %>

  <%= yield %>

</div>

</body>
</html>

app/views/songs/edit.html.erb
<h1>Editing <%= @song.title %></h1>

<%= form_for @song do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %><br>
  <%= f.label :artist_name %>
  <%= f.text_field :artist_name %>
  <br />

  <%= f.submit %>
<% end %>

app/views/songs/index.html.erb
<ul>
  <% @songs.each do |song| %>
  <li><%= link_to song.title, song_path(song) %>-<%= display_artist(song) %></li>
  <% end %>
</ul>
<br>
<%= link_to "Add New Song", new_song_path %>

app/views/songs/new.html.erb
<h1>Create a Song</h1>

<%= render 'form' %>

app/views/songs/show.html.erb
<h1><%= link_to @song.title, song_path(@song) %></h1>
<%= display_artist(@song) %>
<%= link_to "All Songs", songs_path %>